version: '3.9'

services:
  lbf-api:
    build: .
    container_name: lbf-api
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - lbf-db
      - lbf-rabbitMQ
      # - redis
      # - elasticsearch
    networks:
      - lbf-network

  lbf-db:
    image: postgres:latest
    restart: always
    container_name: lbf-db
    environment:
      POSTGRES_PASSWORD: developer
      POSTGRES_USER: developer
      POSTGRES_DB: lbf
    networks:
      - lbf-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   restart: always
  # container_name: lbf-cache
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --loglevel warning
  #   networks:
  #     - lbf-network

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
  #   container_name: lbf-elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - lbf-network
  #   volumes:
  #     - elasticsearch_data:/var/lib/elasticsearch
  lbf-rabbitMQ:
    image: rabbitmq:3.13-management
    container_name: lbfMQ
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - lbf-network

volumes:
  postgres_data: {}
  # elasticsearch_data: {}
networks:
  lbf-network:
    driver: bridge
